name: Test Action
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: Print a sample message
      run: |
        echo "this is a sample action"
